### ISSUE TITLE
version.properties

### ISSUE THREAD

**Issue by CaptainJno** [ethereum/ethereumj#1079]
#1008  This issue still exists. The version.properties still exists in 1.7.3-RELEASE.

**Comment by zilm13** [comment]
@CaptainJno do you have failing example for gradle/maven?
This should be fixed, but may be we've missed something

**Comment by CaptainJno** [comment]
@zilm13  Yes. I download the  1.7.3-RELEASE through gradle.  Then, i unzip the jar and found the version.properties still exists.  
But according to 1008，i think version.properties should be removed. Is this right?

**Comment by zilm13** [comment]
@CaptainJno no, we are not going to remove `version.properties` because it will broke backwards compatibility + we could still have clashes with any other name. So what I've changed: we parse it safely to find `version.properties` which belongs to EthereumJ.

**Comment by CaptainJno** [comment]
@zilm13 So, there will be no more change in this issue ?  Maybe I need to solve my problem in other ways.

**Comment by CaptainJno** [comment]
@zilm13 Both web3j and ethereumj contain version.properties, when i use them together in my android project ,then build it, there wil occur an excepiton "com.android.builder.merge.DuplicateRelativeFileException: More than one file was found with OS independent path 'version.properties" .

**Comment by CaptainJno** [comment]
@zilm13 And if I try to exclude one of them,  my app crashes.

**Comment by zilm13** [comment]
@CaptainJno do you have public repository for this project, so it will be easier for me to test?

**Comment by CaptainJno** [comment]
@zilm13 [ https://github.com/CaptainJno/TestForEthereumj](url)
I create a project to show my problem. It's almost a auto generated project via Android Studio except two extra dependencies in module 'app'.
When you 'Rebuild Project' or 'Run' you will see the exception in the Build window which is in the sidebar.

**Comment by zilm13** [comment]
@CaptainJno Thank you, we will find how to solve this issue and ping you back

**Comment by zilm13** [comment]
@CaptainJno I've checked your sample, it looks currently safe to add following settings to `android` section of your app `build.gradle`:
```
    packagingOptions {
        merge "version.properties"
    }
```
It will merge both `version.properties` in one file (more info in [documentation](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html)) and as they don't have any conflicting fields it will be used by both libraries correctly. It could be an issue one time in the future if we and web3j add some field with the same name, but not currently. I think we could keep it in current state as merging is used only by Android packaging from our feedback and it's resolvable currently.

Please ping me back whether adding following lines to build configuration resolves your issue.

**Comment by CaptainJno** [comment]
@zilm13   I modified the settings according to your method, then I did some tests ,it works well. And I saw a merged version.properties.
I really appreciate what you’ve done for me these days.
